version: '3.8'

services:
  db:
    image: postgres:15.1  # Updated to the latest stable version
    container_name: shared_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared_services
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 30s
      timeout: 10s
      retries: 5

  sonarqube:
    image: sonarqube:10.2-community  # Updated to the latest stable version
    container_name: shared_sonarqube
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SONAR_JDBC_USERNAME: ${DB_USER}
      SONAR_JDBC_PASSWORD: ${DB_PASSWORD}
    ports:
      - "9000:9000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - shared_services

networks:
  shared_services:
    external: true


volumes:
  postgres_data:
